site_name: MLX-Audio
site_description: A text-to-speech and Speech-to-Speech library built on Apple's MLX framework
site_author: MLX-Audio Team
repo_url: https://github.com/yourusername/mlx-audio
repo_name: MLX-Audio

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - API Reference:
    - TTS: api/tts.md
    - Models: api/models.md
    - Server: api/server.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
    - Advanced Features: examples/advanced-features.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true 